version: '2'
services:
  cassandra1:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - 7000:7000
      - 9042:9042

    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - 7001:7000
      - 9043:9042

    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra3:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - 7002:7000
      - 9044:9042

    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  
  cassandra4:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - 7003:7000
      - 9045:9042

    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  
